# Generated by Django 5.0.4 on 2024-04-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('article', models.BigIntegerField(primary_key=True, serialize=False)),
                ('barcode', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('END OF LIFE', 'Eol'), ('FOR SALE', 'Fs'), ('STOP STOCKS', 'Ss')], default='STOP STOCKS', max_length=20)),
                ('set', models.BooleanField(default=False)),
                ('stock', models.IntegerField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('provider_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Info_Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.info')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='products.info')),
            ],
        ),
        migrations.AddIndex(
            model_name='info',
            index=models.Index(fields=['article', 'product_name'], name='products_in_article_63ca96_idx'),
        ),
    ]
